name: todo
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  flutter_riverpod: ^2.5.1
  uuid: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1 # Add the launcher icons package here

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/images/to-do-4783676_1280.png" # Update this path to your icon file location

flutter:
  uses-material-design: true
